# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: j a c o b s u n d s t r o m
description: > # this means to ignore newlines until "baseurl:"
  you can't understand it unless you've been there
repository: https://github.com/woolgathering/woolgathering.github.io
# baseurl: /jacobsundstrom.com  # the subpath of your site, e.g. /blog
# baseurl: /woolgathering.github.io  # the subpath of your site, e.g. /blog
baseurl: /  # the subpath of your site, e.g. /blog
url: https://www.jacobsundstrom.com  # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: standard  # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: jacob sundstrom
email: jacobsundstrom@gmail.com

navigation:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Work
    url: /work
  - text: Events
    url: /events
  - text: Code
    url: /code
  - text: woolgathering
    url: /woolgathering
  # - text: Examples
  #   url: /examples

# projects:
#   - name: git-secret
#     description: A bash-tool to store your private data inside a git repository.
#     link: https://sobolevn.github.io/git-secret
#     image: https://github.com/sobolevn/git-secret/blob/7c9ae0b1853d4c15549027524121b9e40219fe47/images/git-secret-sm.png?raw=true
#   - name: awesome-cryptography
#     description: A curated list of cryptography resources and links.
#     link: https://github.com/sobolevn/awesome-cryptography
#     image: https://pbs.twimg.com/profile_images/751426570607271937/vGxpniun_400x400.jpg
#   - name: ecto_autoslug_field
#     description: Automatically creates slugs for your Ecto models.
#     link: https://github.com/sobolevn/ecto_autoslug_field
#   - name: django-split-settings
#     description: Organize Django settings into multiple files and directories. Easily override and modify settings. Use wildcards and optional settings files.
#     link: https://github.com/sobolevn/django-split-settings
#
# social:
#   - service: github
#     username: woolgathering
#     link: https://github.com/woolgathering
#   - service: twitter
#     username: sobolevn
#     link: https://twitter.com/sobolevn

responsive_image:
  template: _includes/responsive-image.html
  cache: true
  strip: true
  default_quality: 90
  sizes:
    - width: 20 # lq
      quality: 10
    - width: 480  # [Required] How wide the resized image will be.
      quality: 80 # [Optional] Overrides default_quality for this size.
    - width: 800
    - width: 1400
      quality: 90

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-responsive-image

# Google Analytics
google_analytics: UA—128041839-1
